server:
  port : 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springDataDB
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        show-sql: false
        format-sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy