server:
  port : 8081

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:/Users/infinitelambda/Desktop/h2DbTest
    username: sa
    password:
    driverClassName: org.h2.Driver